### ISSUE TITLE
Recording doesn't work with cc mode on?

### ISSUE THREAD

**Issue by khayamy001** [klingtnet/bitwig-extensions#1]
Love that you're working on this!
I tried it out and found that I can't record any notes played with the pad when CC mode is on (after pad remapping). Any idea?

**Comment by klingtnet** [comment]
@khayamy001 What extensions did you use, the one for the AKAI mpk-mini-mk2?

**Comment by khayamy001** [comment]
ah, sorry forgot to specify that!
indeed, it's the one for the akai mpk mini mk2.

**Comment by klingtnet** [comment]
I think this is a bug in Bitwig's extension API. I openend about this over a year ago but got no response: https://answers.bitwig.com/questions/14612/bug-cant-record-notes-created-by-controller-script

**Comment by khayamy001** [comment]
Ah okay, makes sense. How do you work around this? Do you just not use it
for recording?
Thanks for your help btw :)

**Comment by klingtnet** [comment]
At the moment, yes, i.e. I don't use it for recording. Since `answers.bitwig.com` is not very helpful I will write Bitwig's support in order to get answer to my question regarding the extension API.

**Comment by klingtnet** [comment]
Sorry, I need to close this issue since I sold the AKAI controller and will eventually drop support for it.
