### ISSUE TITLE
Mapping of knobs on Midimix

### ISSUE THREAD

**Issue by carlca** [klingtnet/bitwig-extensions#5]
Hello, I am about to take delivery of a new Akai Midimix, and I have been researching scripts to drive it. My ideal arrangement is to have the sliders as track volumes but to have each set of buttons for a track to control the FX Send amount. Is this something that would be easy to achieve using your script, either using the pre-supplied bwextensiom or by modifying the source code?

**Comment by klingtnet** [comment]
@carlca Hi!  

> ... to have the sliders as track volumes.

This is already implemented, so nothing to do here.

>  ... to have each set of buttons for a track to control the FX Send amount.

I am unsure how you want to control the fx send amount with a button (by holding and reassigning the track fader)?  Nonetheless, it should be a straigtforward change in the code.  Feel free to adjust it as you please.

**Comment by carlca** [comment]
Sorry, I should have said "to have each set of *knobs* for a track to control the FX Send amount" 😉 Similar to how this dude is doing it with Ableton... https://www.youtube.com/watch?v=F2Roh_J2EsQ&feature=emb_logo

**Comment by carlca** [comment]
I've been looking at the code and I reckon that all I need to do is to make this change...

Replace the code at lines 68-73:

```
                if (row == 0) {
                    knob.setBinding(remoteControlsPage.getParameter(col).value());
                } else {
                    Send send = trackBank.getItemAt(col).sendBank().getItemAt(row - 1);
                    knob.setBinding(send.value());
                }
```

with the lines:

```
                Send send = trackBank.getItemAt(col).sendBank().getItemAt(row);
                knob.setBinding(send.value());
```

Thus making the assignment of the send controls apply equally to all 3 rows.

What do you think? 😉

**Comment by carlca** [comment]
I tried the above changes but I felt getting run-time Java errors!

I've managed to solve the problem by constructing the patch from scratch using the Flexi / Generic option in the "Driven by Moss" extension.

Cheers,
Carl
