### ISSUE TITLE
In the deprecated repository bitwig-edirol-pcr: add the DEPRECATED warning to the readme

### ISSUE THREAD

**Issue by felixniemeyer** [klingtnet/bitwig-extensions#6]
I would create this issue at the [klingtnet/bitwig-edirol-pcr](https://github.com/klingtnet/bitwig-edirol-pcr) repo, but it's archived. 

That deprecated repo is still the first google result when searching for "roland pcr controller script bitwig". 
I overlooked the deprecation warning in the "About" section on the side. Only when I had troubles building the java project, I realized that it has been deprecated in favor for this repo here. 
I think it would be good, to add the deprecation info from the about section to the README of the deprecated repo as well. 

Thank you for this controller script, great work!

**Comment by klingtnet** [comment]
@felixniemeyer That's absolutely reasonable advice.  I will add the deprecation warning to the README and link to this repository instead.  i'm glad to hear that you like the controller extension 😊
